### ISSUE TITLE
I cannot "make all" for Makefile:616: recipe for target '.build_release/tools/extract_features.bin' failed

### ISSUE THREAD

**Issue by TaihuLight** [choasup/caffe-yolo9000#1]
when I compile the code, encounter the error as follow:
AR -o .build_release/lib/libcaffe.a
LD -o .build_release/lib/libcaffe.so.1.0.0-rc3
CXX/LD -o .build_release/tools/extract_features.bin
CXX/LD -o .build_release/tools/finetune_net.bin
CXX/LD -o .build_release/tools/convert_box_data.bin
CXX/LD -o .build_release/tools/compute_image_mean.bin
.build_release/lib/libcaffe.so: undefined reference to `caffe::curandGetErrorString(curandStatus)'
.build_release/lib/libcaffe.so: undefined reference to `caffe::SyncedMemory::async_gpu_push(CUstream_st* const&)'
.build_release/lib/libcaffe.so: undefined reference to `caffe::cublasGetErrorString(cublasStatus_t)'
collect2: error: ld returned 1 exit status
Makefile:616: recipe for target '.build_release/tools/extract_features.bin' failed
make: *** [.build_release/tools/extract_features.bin] Error 1
make: *** Waiting for unfinished jobs....
.build_release/lib/libcaffe.so: undefined reference to `caffe::curandGetErrorString(curandStatus)'
.build_release/lib/libcaffe.so: undefined reference to `caffe::SyncedMemory::async_gpu_push(CUstream_st* const&)'
.build_release/lib/libcaffe.so: undefined reference to `caffe::cublasGetErrorString(cublasStatus_t)'
collect2: error: ld returned 1 exit status
Makefile:616: recipe for target '.build_release/tools/convert_box_data.bin' failed
make: *** [.build_release/tools/convert_box_data.bin] Error 1
.build_release/lib/libcaffe.so: undefined reference to `caffe::curandGetErrorString(curandStatus)'
.build_release/lib/libcaffe.so: undefined reference to `caffe::SyncedMemory::async_gpu_push(CUstream_st* const&)'
.build_release/lib/libcaffe.so: undefined reference to `caffe::cublasGetErrorString(cublasStatus_t)'
collect2: error: ld returned 1 exit status
Makefile:616: recipe for target '.build_release/tools/compute_image_mean.bin' failed
make: *** [.build_release/tools/compute_image_mean.bin] Error 1
Could you help me for that?

**Comment by choasUp** [comment]
You can try to make BVLC/caffe. If there is no problem, I think it will be right here.

**Comment by TaihuLight** [comment]
I make BLVC/caffe is OK, but make the caffe-yolo as above for many times.

**Comment by choasUp** [comment]
Maybe I can't help you, Try to use anaconda? Opencv 3.0?.....I can sure that code is right to make...
