### ISSUE TITLE
want to test YOLO9000 in caffe

### ISSUE THREAD

**Issue by SunLoveSheep** [choasup/caffe-yolo9000#14]
Hi ChoasUp,

I'm trying to convert YOLO9000 into caffe framework. However, the region layer is not easy to achieve. Really appreciate if you would like to share your code or the converted YOLO9000 caffemodel. Thanks a lot!

My email address: sunyi324@gmail.com

Best Regards,
Mike

**Comment by OPPOA113** [comment]
@choasUp 
would like to share your code? 
email: zengem2017@gmail.com
thankyou

**Comment by chenfsjz** [comment]
email: chenfsjz@gmail.com
thank you!

**Comment by RunZH** [comment]
@choasUp 
What's up!
Have you solved the problem of low mAP and added reorg layer?
I would appreciate it a lot if you could share ur latest code.
My mail address is rickyedwood@gmail.com

**Comment by moliqian** [comment]
Hi. choasUp
would you like to share your code?
email: 1104504290@qq.com
thanks!!!

**Comment by TwistedfateKing** [comment]
Hi.
would you like to share your code?
email: esrobb3@gmail.com
thank you !

**Comment by hewumars** [comment]
Hi.
why the codes was gone?
would you like to share your latest codes?
email: hw5226349@gmail.com
thank you !

**Comment by hewumars** [comment]
请问能分享下caffe yolov2最新的代码吗？ 非常感谢，自己修改网络去训练yolo模型，但是darknet支持的层太少，希望在caffe上面进行训练。 我用您之前代码训练过，但是准确率不高，达不到darknet训练出来的水平，不知道您找到原因没有？
希望回复,多多交流。
hw5226349@gmail.com

**Comment by lisajwhl** [comment]
Hi.
 would you like to share your code?
 email: lisajwhl@gmail.com 
thank you !

**Comment by jmu201521121021** [comment]
Hi,
Could you share your code?
your work is wwll.
my email:863385256@qq.com
thank you!

**Comment by choasup** [comment]
Updated.
