### ISSUE TITLE
Why the codes are gone?

### ISSUE THREAD

**Issue by jinfagang** [choasup/caffe-yolo9000#16]
Empty repo for what purpose

**Comment by hewumars** [comment]
请问能分享下caffe yolov2最新的代码吗？ 非常感谢，自己修改网络去训练yolo模型，但是darknet支持的层太少，希望在caffe上面进行训练。  我用您之前代码训练过，但是准确率不高，达不到darknet训练出来的水平，不知道您找到原因没有？ 
希望回复,多多交流。
hw5226349@gmail.com

**Comment by choasup** [comment]
Updated.
