### ISSUE TITLE
problems training 2-class detector

### ISSUE THREAD

**Issue by vvvv3ummer** [choasUp/caffe-yolo9000#2]
Hi , i want to train a 2-class detector on caffe-yolo9000 , but i can't use the pretrained caffemodel that you provided cause it was trained on VOC which has 20 classes , otherwise it will report the error "Cannot copy param 0 weights from layer 'conv_reg'; shape mismatch.  Source param shape is 125 1024 1 1 (12                 8000); target param shape is 30 1024 1 1 (30720)."Is there some way to convert the yolo v2 weights into caffemodel , or how can i trained without pretrained model? 
Thanks a lot!

**Comment by choasUp** [comment]
'conv_reg' layer in your train_prototxt should rename.
