### ISSUE TITLE
loss diffenece between darknet caffe-yolo9000

### ISSUE THREAD

**Issue by gaojie0105** [choasup/caffe-yolo9000#25]

**Comment by gaojie0105** [comment]
darknet:   l.delta[obj_index] = 0 - l.output[obj_index];
caffe-yolo9000: diff[index + 4] = -1 * noobject_scale_ * (0 - swap_data[index + 4]) * (swap_data[index + 4]) * (1 - swap_data[index + 4]);
按我理解，这部分是是否是前景的loss，这个loss就是L2 loss，求导应该是它本身才对，就像darknet一样，不明白为什么你的偏导会这么复杂，希望得到你的帮助，谢谢

**Comment by choasup** [comment]
caffe-yolo9000: diff[index + 4] = -1 * noobject_scale_ * (0 - swap_data[index + 4]) * (swap_data[index + 4]) * (1 - swap_data[index + 4]);

due to 
p(obj) = sigmoid(swap_data[index + 4])

**Comment by gaojie0105** [comment]
哦，后面两项时sigmoid的导数，谢谢。
  //if (iter < 12800 / bottom[0]->num()){
	    //  vector<Dtype> truth;
	    //  truth.clear();
	    //  truth.push_back((i + .5) / side_); //center of i,j
	    //  truth.push_back((j + .5) / side_);
	    //  truth.push_back((biases_[2 * n]) / side_); //anchor boxes
	    //  truth.push_back((biases_[2 * n + 1]) / side_);
	    //  delta_region_box(truth, swap_data, biases_, n, index, i, j, side_, side_, diff, .01);
	    //}
再请教个问题，这部分代码是什么意思，darknet是有求delta_region_box，delta_region_class的。

**Comment by choasup** [comment]
just like warm-up ... you can refer to darknet.

**Comment by gaojie0105** [comment]
明白了，谢谢
