### ISSUE TITLE
yolo_weights

### ISSUE THREAD

**Issue by shengwangXX** [choasUp/caffe-yolo9000#3]
Hello! In the file 'train_darknet_v3.sh',  weights is gnet_yolo_region_darknet_v3_pretrain_iter_600000.caffemodel. Where is the weights? How can I train to get it?

**Comment by choasUp** [comment]
The pre-trained model is trained by Imagenet data. 1000 classes top-1 accuracy only gets 60%. My pre-trained model is not good enough. I think it is probably caused that I can't train VOC data to get 70% mAP. So I suggested that you can train it by yourself.
