### ISSUE TITLE
loss layer

### ISSUE THREAD

**Issue by wuzhiyang2016** [choasup/caffe-yolo9000#5]
hei，I have a question is that  in detection loss layer, why label is check equal to 1+1+1+4?  why not 1+20+4? hope your reply~

**Comment by choasUp** [comment]
region_loss_layer not detection_loss_layer.
detection loss layer for yolo.

发自我的 iPhone

**Comment by wuzhiyang2016** [comment]
no no no ,is in detection_loss_layer,,code is follow :

int tmp_input_count = side_ * side_ * (num_class_ + (1 + 4) * num_object_);
  // label: isobj, class_label, coordinates
  int tmp_label_count = side_ * side_ * (1 + 1 + 1 + 4);
  CHECK_EQ(input_count, tmp_input_count);
  CHECK_EQ(label_count, tmp_label_count);

why label_count check to side_ * side_ * (1 + 1 + 1 + 4);  ?

**Comment by wuzhiyang2016** [comment]
i want to convert yolo v1 to caffe, just want to detect one class,  a picture is followed 7*7*(1+1+4)labels,if a cell is contain an object's center, I set the cell's 6 values to  1 ,1, x ,y ,w ,h, if the cell isn't have an object , set 0 ,0,0,0,0,0,   it's wrong i have done ? need your help~

**Comment by wuzhiyang2016** [comment]
i want to convert yolo v1 to caffe, just want to detect one class, a picture is followed 7*7(1+1+4)labels,if a cell is contain an object's center, I set the cell's 6 values to 1 ,1, x ,y ,w ,h, if the cell isn't have an object , set 0 ,0,0,0,0,0, it's wrong i have done ? need your help~

**Comment by wuzhiyang2016** [comment]
so i can't understand your code: int tmp_label_count = side_ * side_ * (1 + 1 + 1 + 4);

**Comment by choasUp** [comment]
You can refer to https://github.com/yeahkun/caffe-yolo.
code in box_data_layer::transform_label()
