### ISSUE TITLE
 how to solve the error when ./train_darknet_v3.sh 

### ISSUE THREAD

**Issue by Designbook1** [choasup/caffe-yolo9000#6]
[libprotobuf ERROR google/protobuf/text_format.cc:298] Error parsing text-format caffe.SolverParameter: 12:8: Message type "caffe.SolverParameter" has no field named "stagelr".
F0417 16:28:56.909394 25717 upgrade_proto.cpp:1063] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse SolverParameter file: ./gnet_region_solver_darknet_v3.prototxt
*** Check failure stack trace: ***
    @     0x7fda32843bfd  google::LogMessage::Fail()
    @     0x7fda32845a6f  google::LogMessage::SendToLog()
    @     0x7fda32843793  google::LogMessage::Flush()
    @     0x7fda3284638e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fda38130b8e  caffe::ReadSolverParamsFromTextFileOrDie()
    @           0x409fc1  train()
    @           0x4076bc  main
    @     0x7fda2884fb35  __libc_start_main
    @           0x40817c  (unknown)

**Comment by choasUp** [comment]
Your solver.prototxt has some problem. If you use stagelr, you should set 
`lr_policy: "multifixed" `

**Comment by Designbook1** [comment]
Thank you for your answer，that is the problom！If I set `lr_policy: "multifixed"`  I must compile your caffe not use my own. So with your tip, I solve it.

**Comment by oppo62258801** [comment]
I have a problem when I train my own dataset. The log shows  as follows:
I0517 10:51:16.226722 13269 region_loss_layer.cpp:512] avg_noobj: 0.473491 avg_obj: -nan avg_iou: -nan avg_cat: -nan recall: -nan class_count: 0
....
and the "-nan" can not be stoped even though I changed the initial base_lr.
So did you encounter the same question and can you help me to solve it?

**Comment by choasUp** [comment]
base_lr should be smaller.

choas

**Comment by Designbook1** [comment]
@oppo62258801 Maybe the data label is bad, you should protect it. Decrease the base lr is may also help you.

**Comment by oppo62258801** [comment]
@choasUp 
you mean decrease the following values?
stagelr: 0.0001
stagelr: 0.001
stagelr: 0.0001
stagelr: 0.00001

**Comment by oppo62258801** [comment]
@Designbook1 
I have tried to decrease the stagelr. And I even changed the lr_policy from to multifixed to fixed. They all don not work.
My dataset has four classes, but there is the "-nan" problem. But when I try to change four classes to only one class, it still does not work.

**Comment by evenctit** [comment]
@oppo62258801 hi friend, did you resolve the nan issue? I encountered this issue.
I want to use yolo9000 to detect text box in natural scene pictures, but I got below issue, do you have any idea? thanks. 
Region Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.518544, Avg Recall: -nan,  count: 0
34: 345.566132, 340.394623 avg, 0.000000 rate, 0.152061 seconds, 34 images
Loaded: 0.000026 seconds
