### ISSUE TITLE
Problems detection for my own data

### ISSUE THREAD

**Issue by dongyinl** [choasUp/caffe-yolo9000#7]
Hi, I want to train a 40-classes detector with yolo9000. After changing num_class and num_output, I run train.sh. The data in train.log is ok, and I try to run test.sh( I've changed the number 'int num_class = ' in test_detection.cpp, and make again). However the data in test.log is rediculous (eg. iter_loss=260). What else I have to change in test_detection.cpp?
I also try to run test.ipynb, and change the following code:
label_name ={??}
swap = np.zeros((13*13,5,??))
for c in range(??):
swap[h*13+w][c/??][c%??]  = res[c][h][w]
 for p in range(??):
But the output picture can't show anything, so how can I deal with it? 
Thanks!

**Comment by dongyinl** [comment]
I've made it.

**Comment by OPPOA113** [comment]
@dongyinl 
i can not train my own data normally.can you share you caffe code for yolov2 . thanks. email:2875507852@qq.com
